[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
backgroundColor = "#000000"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"
primaryColor = "#1f77b4"

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
level = "error"

[client]
showErrorDetails = false
toolbarMode = "minimal" 